В этом блокноте мы научимся строить график японских свечей.

Для начала подключаем библиотеку pandas и загружаем интересующий нас файл при помощи метода `read_csv(file_name, delimeter, index_col, decimal, usecols, header, ...)`. Подробное описание можно найти по [ссылке](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

Скачаем файл с гугл диска (этот шаг можно пропустить и подгрузить свой файл сразу в виртуальное окружение)

In [1]:
!gdown 1ymmCS5jJc4Jh1Kq0kzYcFAegrPw9cm9L

Downloading...
From: https://drive.google.com/uc?id=1ymmCS5jJc4Jh1Kq0kzYcFAegrPw9cm9L
To: /content/SPFB.RTS-12.18_180901_181231.csv
100% 5.71M/5.71M [00:00<00:00, 284MB/s]

**Используйте файл с данными из своего варианта задания!!!**

Считаем файл в датафрейм

In [2]:
import pandas as pd
data = pd.read_csv('/content/SPFB.RTS-12.18_180901_181231.csv', 
                       delimiter=',', 
                       decimal='.')

 Посмотрим на наши данные. Похоже, они загрузились правильно.

---

Можно окинуть взглядом и весь набор данных:

In [3]:
data

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
0,SPFB.RTS-12.18,1,03/09/18,10:01,107900.0,108060.0,107900.0,108030.0,3
1,SPFB.RTS-12.18,1,03/09/18,10:02,107960.0,107960.0,107960.0,107960.0,5
2,SPFB.RTS-12.18,1,03/09/18,10:04,108000.0,108000.0,108000.0,108000.0,8
3,SPFB.RTS-12.18,1,03/09/18,10:05,108000.0,108000.0,108000.0,108000.0,1
4,SPFB.RTS-12.18,1,03/09/18,10:08,108080.0,108080.0,108080.0,108080.0,1
...,...,...,...,...,...,...,...,...,...
58965,SPFB.RTS-12.18,1,20/12/18,18:40,109380.0,109380.0,109380.0,109380.0,1
58966,SPFB.RTS-12.18,1,20/12/18,18:41,109380.0,109390.0,109380.0,109390.0,10
58967,SPFB.RTS-12.18,1,20/12/18,18:43,109380.0,109390.0,109380.0,109390.0,12
58968,SPFB.RTS-12.18,1,20/12/18,18:44,109390.0,109390.0,109390.0,109390.0,3
58969,SPFB.RTS-12.18,1,20/12/18,18:45,109390.0,109390.0,109380.0,109380.0,3

Преобразуем дату в удобный для дальнейшего формат, склеив дату и время

In [4]:
data['DATE'] = data['<DATE>'] + ' ' + data['<TIME>'] 
data.head()

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,DATE
0,SPFB.RTS-12.18,1,03/09/18,10:01,107900.0,108060.0,107900.0,108030.0,3,03/09/18 10:01
1,SPFB.RTS-12.18,1,03/09/18,10:02,107960.0,107960.0,107960.0,107960.0,5,03/09/18 10:02
2,SPFB.RTS-12.18,1,03/09/18,10:04,108000.0,108000.0,108000.0,108000.0,8,03/09/18 10:04
3,SPFB.RTS-12.18,1,03/09/18,10:05,108000.0,108000.0,108000.0,108000.0,1,03/09/18 10:05
4,SPFB.RTS-12.18,1,03/09/18,10:08,108080.0,108080.0,108080.0,108080.0,1,03/09/18 10:08

Поработаем над форматом времени. Для этого переведем строковые данные, показывающие время, в специальный объект в Python.

In [5]:
data['DATE'] = pd.to_datetime(data['DATE'], format="%d/%m/%y %H:%M")
data.head()

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,DATE
0,SPFB.RTS-12.18,1,03/09/18,10:01,107900.0,108060.0,107900.0,108030.0,3,2018-09-03 10:01:00
1,SPFB.RTS-12.18,1,03/09/18,10:02,107960.0,107960.0,107960.0,107960.0,5,2018-09-03 10:02:00
2,SPFB.RTS-12.18,1,03/09/18,10:04,108000.0,108000.0,108000.0,108000.0,8,2018-09-03 10:04:00
3,SPFB.RTS-12.18,1,03/09/18,10:05,108000.0,108000.0,108000.0,108000.0,1,2018-09-03 10:05:00
4,SPFB.RTS-12.18,1,03/09/18,10:08,108080.0,108080.0,108080.0,108080.0,1,2018-09-03 10:08:00

Сформируем интересующую нас выборку

In [6]:
df_filtered = data[data['DATE'].dt.strftime('%Y-%m-%d') == '2018-09-25']

Теперь полная дата будет для нас индеком объектов

In [7]:
df_filtered = df_filtered.set_index('DATE')
df_filtered

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
DATE,,,,,,,,,
2018-09-25 10:01:00,SPFB.RTS-12.18,1,25/09/18,10:01,115350.0,115740.0,115320.0,115540.0,3063
2018-09-25 10:02:00,SPFB.RTS-12.18,1,25/09/18,10:02,115540.0,115560.0,115350.0,115400.0,2128
2018-09-25 10:03:00,SPFB.RTS-12.18,1,25/09/18,10:03,115390.0,115400.0,115330.0,115370.0,1150
2018-09-25 10:04:00,SPFB.RTS-12.18,1,25/09/18,10:04,115380.0,115400.0,115340.0,115390.0,1052
2018-09-25 10:05:00,SPFB.RTS-12.18,1,25/09/18,10:05,115390.0,115400.0,115270.0,115370.0,2008
...,...,...,...,...,...,...,...,...,...
2018-09-25 23:46:00,SPFB.RTS-12.18,1,25/09/18,23:46,115500.0,115530.0,115490.0,115530.0,118
2018-09-25 23:47:00,SPFB.RTS-12.18,1,25/09/18,23:47,115530.0,115580.0,115520.0,115580.0,228
2018-09-25 23:48:00,SPFB.RTS-12.18,1,25/09/18,23:48,115570.0,115610.0,115550.0,115590.0,236
2018-09-25 23:49:00,SPFB.RTS-12.18,1,25/09/18,23:49,115590.0,115630.0,115570.0,115570.0,405
2018-09-25 23:50:00,SPFB.RTS-12.18,1,25/09/18,23:50,115560.0,115580.0,115450.0,115490.0,380

Выберем только интересующие для построения столбцы:

In [8]:
df_filtered = df_filtered[['<OPEN>','<HIGH>','<LOW>','<CLOSE>']]

Переименуем (для удобства) столбцы:

In [9]:
df_filtered.columns =['open', 'high', 'low', 'close']
df_filtered.head()

                         open      high       low     close
DATE
2018-09-25 10:01:00  115350.0  115740.0  115320.0  115540.0
2018-09-25 10:02:00  115540.0  115560.0  115350.0  115400.0
2018-09-25 10:03:00  115390.0  115400.0  115330.0  115370.0
2018-09-25 10:04:00  115380.0  115400.0  115340.0  115390.0
2018-09-25 10:05:00  115390.0  115400.0  115270.0  115370.0

Проведем агрегацию данных для построения графика свечей ([документация](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html)):

In [10]:
d2 = df_filtered.resample('1H').agg({'open':'first',
                                     'high':'max',
                                     'low':'min',
                                     'close':'last'})

In [11]:
d2

                         open      high       low     close
DATE
2018-09-25 10:00:00  115350.0  115740.0  114450.0  114700.0
2018-09-25 11:00:00  114700.0  114970.0  114220.0  114890.0
2018-09-25 12:00:00  114890.0  115280.0  114640.0  114950.0
2018-09-25 13:00:00  114950.0  115320.0  114720.0  115280.0
2018-09-25 14:00:00  115280.0  115670.0  115050.0  115300.0
2018-09-25 15:00:00  115320.0  115480.0  114980.0  115260.0
2018-09-25 16:00:00  115260.0  115810.0  115030.0  115740.0
2018-09-25 17:00:00  115730.0  115830.0  115390.0  115650.0
2018-09-25 18:00:00  115650.0  115760.0  115400.0  115430.0
2018-09-25 19:00:00  115510.0  115580.0  115220.0  115580.0
2018-09-25 20:00:00  115580.0  115640.0  115420.0  115490.0
2018-09-25 21:00:00  115480.0  115580.0  115460.0  115520.0
2018-09-25 22:00:00  115530.0  115730.0  115520.0  115600.0
2018-09-25 23:00:00  115600.0  115680.0  115450.0  115490.0

Осталось подключить необходимую библиотеку и построить:

In [12]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Candlestick(x=d2.index,
                open=d2['open'],
                high=d2['high'],
                low=d2['low'],
                close=d2['close'])])

fig.show()